
/*
 * ConsultasBoletas.java
 *
 * Created @author elaprendiz http://www.youtube.com/user/JleoD7
 */
package Formulario;

import static Formulario.CajaRegistradora.horaact;
import static Formulario.Factura.tbdet;
import static Formulario.IngresoSistema.usuario;
import claseConectar.conectar;
import java.net.URL;
//import java.awt.Image;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.*;
//import javax.swing.Icon;
//import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public final class ConsultasVentas extends javax.swing.JInternalFrame {

    /** Creates new form ConsultasBoletas */
    public ConsultasVentas() {
        initComponents();
        
        jLabelFecha.setText(fechaact());
        ComboboxVendedor();
        //rdbntodos.setSelected(true);
        fecha();
        
        Cargar("", CajaRegistradora.fechaact(), "", "", "", "");
        bloquear();
        calcular();
        txtTotalCantidad.setEditable(false);
        txtTotalMonto.setEditable(false);
        //cargarImagen();
        
    }
    private int cont=1;
    private void fecha(){
        try {
            jDateChooser1.setEnabled(true);
            rdbbnfecha.setSelected(true);
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaDate = formato.parse(CajaRegistradora.fechaact());
            jDateChooser1.setDate(fechaDate);
        } catch (ParseException e) {
            System.err.println("Error! "+e.getMessage());
        }
    }
    void inicio(){
       System.out.println("cont "+cont);
       txtproducto.setText("");
       rdbnProducto.setSelected(false);
       rdbbnfecha.setSelected(false);
       rdbbnTipoPrecio.setSelected(false);
       rdbnTipoVenta.setSelected(false);
       rdbnVendedor.setSelected(false);
       cbTipoPrecio.setSelectedItem("Todos");
       cbTipoVenta.setSelectedItem("Todos");
       cbVendedor.setSelectedItem("Seleccionar Opcion");
    }
    
    /*void cargarImagen(){
      //  "/Imagenes/negocios.jpg"
        ImageIcon fot = new ImageIcon("/Imagenes/negocios.jpg");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        this.repaint();
    }*/
            

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mneliminar = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbboletas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rdbbnfecha = new javax.swing.JRadioButton();
        rdbnProducto = new javax.swing.JRadioButton();
        rdbntodos = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtproducto = new javax.swing.JTextField();
        btnbuscador = new javax.swing.JButton();
        rdbnTipoVenta = new javax.swing.JRadioButton();
        cbTipoVenta = new javax.swing.JComboBox<>();
        cbTipoPrecio = new javax.swing.JComboBox<>();
        rdbbnTipoPrecio = new javax.swing.JRadioButton();
        cbVendedor = new javax.swing.JComboBox<>();
        rdbnVendedor = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        btnimforme = new javax.swing.JButton();
        btnImprimir1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalMonto = new javax.swing.JTextField();

        mneliminar.setText("mneliminar");
        mneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mneliminar);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTAS DE VENTAS");
        setMaximumSize(new java.awt.Dimension(856, 572));
        setMinimumSize(new java.awt.Dimension(856, 572));
        setPreferredSize(new java.awt.Dimension(856, 572));

        jPanel1.setBackground(new java.awt.Color(227, 255, 255));

        tbboletas.setAutoCreateRowSorter(true);
        tbboletas.setBackground(new java.awt.Color(0, 153, 255));
        tbboletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbboletas.setToolTipText("");
        tbboletas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbboletas);

        jPanel2.setBackground(new java.awt.Color(240, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSQUEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        rdbbnfecha.setText("Mostrar por Fecha");
        rdbbnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbnfechaActionPerformed(evt);
            }
        });

        rdbnProducto.setText("Mostrar Por Prod:");
        rdbnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnProductoActionPerformed(evt);
            }
        });

        rdbntodos.setText("Mostrar todas:");
        rdbntodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbntodosActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(0, 153, 255));

        txtproducto.setBackground(new java.awt.Color(0, 153, 255));

        btnbuscador.setBackground(new java.awt.Color(0, 102, 255));
        btnbuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnbuscador.setBorder(null);
        btnbuscador.setBorderPainted(false);
        btnbuscador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscador.setIconTextGap(1);
        btnbuscador.setOpaque(false);
        btnbuscador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnbuscador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarSelected.png"))); // NOI18N
        btnbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscadorActionPerformed(evt);
            }
        });

        rdbnTipoVenta.setText("Mostrar por : ");
        rdbnTipoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnTipoVentaActionPerformed(evt);
            }
        });

        cbTipoVenta.setBackground(new java.awt.Color(0, 153, 255));
        cbTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Boleta", "Factura", "Ticket" }));
        cbTipoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoVentaActionPerformed(evt);
            }
        });

        cbTipoPrecio.setBackground(new java.awt.Color(0, 153, 255));
        cbTipoPrecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mayorista", "Minorista" }));
        cbTipoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPrecioActionPerformed(evt);
            }
        });

        rdbbnTipoPrecio.setText("Mostrar por Tipo");
        rdbbnTipoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbbnTipoPrecioActionPerformed(evt);
            }
        });

        cbVendedor.setBackground(new java.awt.Color(0, 153, 255));
        cbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVendedorActionPerformed(evt);
            }
        });

        rdbnVendedor.setText("Mostrar x Vend : ");
        rdbnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbnVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbbnfecha)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbnProducto)
                            .addComponent(rdbbnTipoPrecio))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(rdbnTipoVenta)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbntodos)
                            .addComponent(rdbnVendedor))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbnProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbnVendedor)
                    .addComponent(rdbbnfecha)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbbnTipoPrecio)
                    .addComponent(cbTipoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbntodos)))
            .addComponent(btnbuscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbnTipoVenta)
                    .addComponent(cbTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(234, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Reporte de Ventas al");

        jLabelFecha.setBackground(new java.awt.Color(240, 255, 255));
        jLabelFecha.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnimforme.setBackground(new java.awt.Color(0, 102, 255));
        btnimforme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnimforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.JPG"))); // NOI18N
        btnimforme.setText("Imforme");
        btnimforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimformeActionPerformed(evt);
            }
        });

        btnImprimir1.setBackground(new java.awt.Color(0, 102, 255));
        btnImprimir1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imprimir.png"))); // NOI18N
        btnImprimir1.setText("Imprimir ");
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setText("Total Cantidad:");

        txtTotalCantidad.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtTotalCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCantidadActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setText("Total Monto: S/.");

        txtTotalMonto.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtTotalMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnimforme, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTotalMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnimforme, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void rdbnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnProductoActionPerformed
// TODO add your handling code here: 
    System.out.println("cont "+cont);
    txtproducto.setEnabled(true);
    if(rdbnProducto.isSelected()){ txtproducto.setEnabled(true);cont=cont+1;if(cont==1){rdbntodos.setSelected(false);}}
    if(!rdbnProducto.isSelected()){ txtproducto.setEnabled(false);cont=cont-1;}
    if(cont==0) rdbntodos.setSelected(true);
    System.out.println("Formulario.ConsultasVentas.rdbnProductoActionPerformed() "+cont);
    System.out.println("cont "+cont);
}//GEN-LAST:event_rdbnProductoActionPerformed

private void rdbbnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbnfechaActionPerformed
// TODO add your handling code here:
    jDateChooser1.setEnabled(true);
    if(rdbbnfecha.isSelected()){ jDateChooser1.setEnabled(true);cont=cont+1;if(cont==1){rdbntodos.setSelected(false);}}
    if(!rdbbnfecha.isSelected()){ jDateChooser1.setEnabled(false);cont=cont-1;}
    if(cont==0) rdbntodos.setSelected(true);
    System.out.println("Formulario.ConsultasVentas.rdbnProductoActionPerformed() "+cont);
}//GEN-LAST:event_rdbbnfechaActionPerformed

private void rdbntodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbntodosActionPerformed
// TODO add your handling code here:
if(rdbntodos.isSelected()){
    rdbbnTipoPrecio.setSelected(false);
    rdbbnfecha.setSelected(false);
    rdbnProducto.setSelected(false);
    rdbnTipoVenta.setSelected(false);
    rdbnVendedor.setSelected(false);
    bloquear();
    cont=0;
}
 
    
    
}//GEN-LAST:event_rdbntodosActionPerformed
private void bloquear(){
    txtproducto.setEnabled(false);
    jDateChooser1.setEnabled(false);
    cbTipoPrecio.setEnabled(false);
    cbTipoVenta.setEnabled(false);
    cbVendedor.setEnabled(false);
}

private void btnbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscadorActionPerformed
// TODO add your handling code here:
    
    String producto="",fecha="",TipoVenta="",comprobante="",vendedor="", consulta="";
    if(rdbnProducto.isSelected()==true)
    {
        producto=txtproducto.getText();
        
    }
    if(rdbbnfecha.isSelected()==true)
    {
        Date Fech=jDateChooser1.getDate();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
        fecha =""+formatofecha.format(Fech);
    }
    if(rdbbnTipoPrecio.isSelected()==true){
        TipoVenta = cbTipoPrecio.getSelectedItem().toString();
    }
    if(rdbnTipoVenta.isSelected()==true){
        comprobante = cbTipoVenta.getSelectedItem().toString();
    }
    if(rdbnVendedor.isSelected()==true){
        vendedor = cbVendedor.getSelectedItem().toString();
    }
    Cargar(producto, fecha, TipoVenta, comprobante, vendedor, consulta);
    calcular();
}//GEN-LAST:event_btnbuscadorActionPerformed
private void Cargar(String producto,String fecha,String TipoVenta,String comprobante,String vendedor,String consulta){
    
    String factura = "select detallefactura.des_pro,detallefactura.talla_prod,detallefactura.cod_color,detallefactura.cant_pro,\n" +
"	factura.total,vendedor.nom_ven,factura.fec_fac,factura.hora_factura,'FACTURA' as Comprobante, factura.tipoVenta\n" +
"	from detallefactura\n" +
"	inner join factura\n" +
"	on detallefactura.num_fac=factura.num_fac and concat(detallefactura.des_pro,' ',detallefactura.talla_prod) like '%"+producto+"%'\n" +
"	and factura.fec_fac like '%"+fecha+"%' and factura.tipoVenta like '%"+TipoVenta+"%' \n" +
"	inner join vendedor\n" +
"	on factura.cod_ven=vendedor.cod_ven	 and vendedor.nom_ven like '%"+vendedor+"%'	";
    String boleta = "select detalleboleta.des_pro,detalleboleta.talla_prod,detalleboleta.cod_color,detalleboleta.cant_pro,\n" +
"	boleta.pre_tot,vendedor.nom_ven,boleta.fecha,boleta.hora_boleta,'BOLETA' as Comprobante, boleta.tipoVenta\n" +
"	from  detalleboleta\n" +
"	inner join boleta\n" +
"	on boleta.num_bol=detalleboleta.num_bol  and concat(detalleboleta.des_pro,' ',detalleboleta.talla_prod) like '%"+producto+"%'\n" +
"	and boleta.fecha like '%"+fecha+"%' and boleta.tipoVenta like '%"+TipoVenta+"%' \n" +
"	inner join vendedor\n" +
"	on boleta.cod_ven=vendedor.cod_ven and vendedor.nom_ven like '%"+vendedor+"%'	";
    String NotaVenta = "	select producto.descripcion,DetalleCajaRegistradora.cod_talla,DetalleCajaRegistradora.cod_color,DetalleCajaRegistradora.cantidad,\n" +
"	DetalleCajaRegistradora.pre_venta,vendedor.nom_ven, CajaRegistradora.fecha,CajaRegistradora.hora_boleta,'NOTA VENTA' as Comprobante, DetalleCajaRegistradora.tipoVenta\n" +
"	from DetalleCajaRegistradora\n" +
"	inner join CajaRegistradora\n" +
"	on CajaRegistradora.num_caj=DetalleCajaRegistradora.num_caj \n" +
"	inner join producto\n" +
"	on producto.cod_pro=DetalleCajaRegistradora.cod_pro and concat(producto.descripcion,' ',DetalleCajaRegistradora.cod_talla) like '%"+producto+"%'\n" +
"	and CajaRegistradora.fecha like '%"+fecha+"%' and DetalleCajaRegistradora.tipoVenta like '%"+TipoVenta+"%' \n" +
"	join vendedor\n" +
"	on vendedor.cod_ven=CajaRegistradora.cod_ven and vendedor.nom_ven like '%"+vendedor+"%'	";
    if(rdbntodos.isSelected()==true)
    {
       producto="";fecha="";TipoVenta="";comprobante="";vendedor="";
       txtproducto.setText("");
       rdbnProducto.setSelected(false);
       rdbbnfecha.setSelected(false);
       rdbbnTipoPrecio.setSelected(false);
       rdbnTipoVenta.setSelected(false);
       rdbnVendedor.setSelected(false);
       cbTipoPrecio.setSelectedItem("Todos");
       cbTipoVenta.setSelectedItem("Todos");
       cbVendedor.setSelectedItem("Seleccionar Opcion");
       consulta= factura+" UNION "+boleta+" UNION "+NotaVenta;
    }
    switch ( comprobante ) {
      case "Boleta":
           consulta = boleta;
           break;
      case "Factura":
           consulta = factura;
           break;
      case "Ticket":
           consulta = NotaVenta;
           break;

      default:
           consulta= factura+" UNION "+boleta+" UNION "+NotaVenta;
           break;  
    }

        DefaultTableModel tabla= new DefaultTableModel()
        {
             @Override
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        String []titulos={"PRODUCTO","TALLA","COLOR","CANTIDAD","MONTO","VENDEDOR","FECHA","HORA","COMPROBANTE","TIPO VENTA"};
        tabla.setColumnIdentifiers(titulos);
        TableRowSorter sorter = new TableRowSorter(tabla);
        tbboletas.setModel(tabla);
        tbboletas.setRowSorter(sorter);
        String []Datos= new String [11];
        try {
            Statement st = cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            while(rs.next())
            {
                Datos[0]=rs.getString(1);
                Datos[1]=rs.getString(2);
                Datos[2]=rs.getString(3);
                Datos[3]=rs.getString(4);
                Datos[4]=rs.getString(5);
                Datos[5]=rs.getString(6);    
                Datos[6]=rs.getString(7);
                Datos[7]=rs.getString(8);
                Datos[8]=rs.getString(9);
                Datos[9]=rs.getString(10);
                tabla.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
}
private void mneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneliminarActionPerformed
// TODO add your handling code here:
    /*int fila=tbboletas.getSelectedRow();
    if(fila>=0)
    {
        String cod=tbboletas.getValueAt(fila, 0).toString();
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE FROM boleta WHERE num_bol='"+cod+"'");
                pst.executeUpdate();
                rdbntodos.setSelected(true);
                Cargar("", "", "", "", "", "");
            } catch (SQLException ex) {
                Logger.getLogger(ConsultasVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    else
    {
        JOptionPane.showMessageDialog(this, "Seleccione alguna fila");
    }*/
}//GEN-LAST:event_mneliminarActionPerformed

    private void rdbnTipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnTipoVentaActionPerformed
        // TODO add your handling code here:
       
        cbTipoVenta.setEnabled(true);
         if(rdbnTipoVenta.isSelected()){ cbTipoVenta.setEnabled(true);cont=cont+1;if(cont==1){rdbntodos.setSelected(false);}}
        if(!rdbnTipoVenta.isSelected()){ cbTipoVenta.setEnabled(false);cont=cont-1;}
        if(cont==0) rdbntodos.setSelected(true);
        System.out.println("Formulario.ConsultasVentas.rdbnProductoActionPerformed() "+cont);
    }//GEN-LAST:event_rdbnTipoVentaActionPerformed

    private void cbTipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoVentaActionPerformed

    private void cbTipoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoPrecioActionPerformed

    private void rdbbnTipoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbbnTipoPrecioActionPerformed
        // TODO add your handling code here:
        System.out.println("cont "+cont);
        cbTipoPrecio.setEnabled(true);
        if(rdbbnTipoPrecio.isSelected()){ cbTipoPrecio.setEnabled(true);cont=cont+1;if(cont==1){rdbntodos.setSelected(false);}}
        if(!rdbbnTipoPrecio.isSelected()){ cbTipoPrecio.setEnabled(false);cont=cont-1;}
        if(cont==0) rdbntodos.setSelected(true);
        System.out.println("Formulario.ConsultasVentas.rdbnProductoActionPerformed() "+cont);
    }//GEN-LAST:event_rdbbnTipoPrecioActionPerformed

    private void cbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVendedorActionPerformed

    private void rdbnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbnVendedorActionPerformed
        // TODO add your handling code here:
        rdbnVendedor.setEnabled(true);
        if(rdbnVendedor.isSelected()){ cbVendedor.setEnabled(true);cont=cont+1;if(cont==1){rdbntodos.setSelected(false);}}
        if(!rdbnVendedor.isSelected()){ cbVendedor.setEnabled(false);cont=cont-1;}
        if(cont==0) rdbntodos.setSelected(true);
        System.out.println("Formulario.ConsultasVentas.rdbnProductoActionPerformed() "+cont);
    }//GEN-LAST:event_rdbnVendedorActionPerformed

    private void btnimformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimformeActionPerformed
        // TODO add your handling code here:
       // Imprimir mandar = new Imprimir();
       // mandar.utilJTablePrint(tbproductos, jInternalFrame1.getTitle(), "Luis Ramos", true);
       reporte();
    }//GEN-LAST:event_btnimformeActionPerformed

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
        // TODO add your handling code her
        imprimir();
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void txtTotalCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCantidadActionPerformed

    private void txtTotalMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMontoActionPerformed
 
    private void ComboboxVendedor()
    {
    //Creamos la Consulta SQL
    //Establecemos bloque try-catch-finally
    try {
        cbVendedor.addItem("Seleccionar Opcion");
        String cons="	select nom_ven from vendedor\n" +
"	order by nom_ven";
        Statement st2= cn.createStatement();
        ResultSet rs = st2.executeQuery(cons);

        //LLenamos nuestro ComboBox

        while(rs.next()){
           cbVendedor.addItem(rs.getString("nom_ven"));
           // System.out.println("Formulario.IngresoProductos.ComboboxCodPro()"+rs.getString("cod_pro"));
        } 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());   
        }
    }
    
        void calcular()
    {
        String pre;
        String can;
        double subtotal=0;
        double precio;
        int cantidad;
        int imp=0;
        
            /*can=Integer.parseInt(cant);
            imp=pre*can;
            dato[4]=Float.toString(imp);*/
        
        for(int i=0;i<tbboletas.getRowCount();i++)
        {
            pre=tbboletas.getValueAt(i, 4).toString();
            can=tbboletas.getValueAt(i, 3).toString();
            precio=Double.parseDouble(pre);
            cantidad=Integer.parseInt(can);
            imp=imp+cantidad;
            subtotal=subtotal+precio;
            // txtcod.setText(""+Math.rint(c*100)/100)   
        }
        txtTotalCantidad.setText(Integer.toString(imp));
        txtTotalMonto.setText(""+Math.rint(subtotal*100)/100);
       /* txtsubtotal.setText(Double.toString(subtotal));
        txtigv.setText(""+Math.rint(igv*100)/100);
        txttotal.setText(""+Math.rint(total*100)/100);*/
        
            
    }
     public void reporte(){
          ConsultaVenta em;// Instaciamos la clase empleado
         int fila=1;
        List <ConsultaVenta>lista = new ArrayList<>(); //Creamos una lista de empleados con ArrayList para obtener cada empleado
        for(int i=0; i<tbboletas.getRowCount(); i++){ // Iterena cada fila de la tabla
            em = new ConsultaVenta(tbboletas.getValueAt(i, 0).toString(),tbboletas.getValueAt(i,1).toString(), //Tomamos de la tabla el valor de cada columna y creamos un objeto empleado
            tbboletas.getValueAt(i, 2).toString(),tbboletas.getValueAt(i, 3).toString(),tbboletas.getValueAt(i,4).toString(),tbboletas.getValueAt(i, 5).toString(),tbboletas.getValueAt(i, 6).toString(),
            tbboletas.getValueAt(i, 7).toString(),tbboletas.getValueAt(i, 8).toString(),tbboletas.getValueAt(i, 9).toString(),Integer.toString(fila));
            lista.add(em); //Agregamos el objeto empleado a la lista
           // System.out.println("imprimir "+em.codigo);
           fila=fila+1;
        }
        JasperReport reporte; // Instaciamos el objeto reporte
        //String path = "C:\\Users\\Luis Ramos\\Desktop\\ventas2\\Sistema de ventas_3\\ProyectoCompleto\\tienda\\src\\Formulario\\reportTicket.jasper"; //Ponemos la localizacion del reporte creado
        URL path = this.getClass().getResource("reportVentas.jasper");
        try {
            reporte = (JasperReport) JRLoader.loadObject(path); //Se carga el reporte de su localizacion
            Map parametro = new HashMap();
            parametro.put("product",txtTotalCantidad.getText());
            parametro.put("ingreso",txtTotalMonto.getText());
     
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, new JRBeanCollectionDataSource(lista)); //Agregamos los parametros plos parametros para llenar el reporte
            JasperViewer viewer = new JasperViewer(jprint, false); //Se crea la vista del reportes
            //viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Se declara con dispose_on_close para que no se cierre el programa cuando se cierre el reporte
            viewer.setVisible(true); //Se vizualiza el reporte
            viewer.setTitle("Visor");
        } catch (JRException ex) {
            System.out.printf(ex.getMessage());
        }
    }
    public void imprimir(){
         ConsultaVenta em;// Instaciamos la clase empleado
         int fila=1;
        List <ConsultaVenta>lista = new ArrayList<>(); //Creamos una lista de empleados con ArrayList para obtener cada empleado
        for(int i=0; i<tbboletas.getRowCount(); i++){ // Iterena cada fila de la tabla
            em = new ConsultaVenta(tbboletas.getValueAt(i, 0).toString(),tbboletas.getValueAt(i,1).toString(), //Tomamos de la tabla el valor de cada columna y creamos un objeto empleado
            tbboletas.getValueAt(i, 2).toString(),tbboletas.getValueAt(i, 3).toString(),tbboletas.getValueAt(i,4).toString(),tbboletas.getValueAt(i, 5).toString(),tbboletas.getValueAt(i, 6).toString(),
            tbboletas.getValueAt(i, 7).toString(),tbboletas.getValueAt(i, 8).toString(),tbboletas.getValueAt(i, 9).toString(),Integer.toString(fila));
            lista.add(em); //Agregamos el objeto empleado a la lista
           // System.out.println("imprimir "+em.codigo);
           fila=fila+1;
        }
        JasperReport reporte; // Instaciamos el objeto reporte
        //String path = "C:\\Users\\Luis Ramos\\Desktop\\ventas2\\Sistema de ventas_3\\ProyectoCompleto\\tienda\\src\\Formulario\\reportTicket.jasper"; //Ponemos la localizacion del reporte creado
        URL path = this.getClass().getResource("reportVentas.jasper");
        try {
            reporte = (JasperReport) JRLoader.loadObject(path); //Se carga el reporte de su localizacion
            Map parametro = new HashMap();
            parametro.put("product",txtTotalCantidad.getText());
            parametro.put("ingreso",txtTotalMonto.getText());
     
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, new JRBeanCollectionDataSource(lista)); //Agregamos los parametros para llenar el reporte
            JasperPrintManager.printReport(jprint, true);  
        } catch (JRException ex) {
            System.out.printf(ex.getMessage());
        }
    }
    public static String fechaact(){
        Date fecha= new Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);  
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnbuscador;
    private javax.swing.JButton btnimforme;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipoPrecio;
    private javax.swing.JComboBox<String> cbTipoVenta;
    private javax.swing.JComboBox<String> cbVendedor;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem mneliminar;
    private javax.swing.JRadioButton rdbbnTipoPrecio;
    private javax.swing.JRadioButton rdbbnfecha;
    private javax.swing.JRadioButton rdbnProducto;
    private javax.swing.JRadioButton rdbnTipoVenta;
    private javax.swing.JRadioButton rdbnVendedor;
    private javax.swing.JRadioButton rdbntodos;
    public static javax.swing.JTable tbboletas;
    private javax.swing.JTextField txtTotalCantidad;
    private javax.swing.JTextField txtTotalMonto;
    private javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables
conectar cc= new conectar();
Connection cn = cc.conexion();
}
